// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const challengeAnalytics = `-- name: ChallengeAnalytics :one
SELECT
    COUNT(uc.id) FILTER (WHERE uc.status = 'active')::int AS active_count,
    COUNT(uc.id) FILTER (WHERE uc.status = 'left')::int AS left_count,
    COUNT(uc.id) FILTER (WHERE uc.status = 'disqualified')::int AS disqualified_count,
    COALESCE(AVG(s.current_streak) FILTER (WHERE uc.status = 'active'), 0)::float8 AS avg_current_streak,
    (
        SELECT COUNT(DISTINCT c.user_challenge_id)
        FROM checkins c
        JOIN user_challenges uc2 ON uc2.id = c.user_challenge_id
        WHERE uc2.challenge_id = $1 AND uc2.status = 'active' AND c.date = CURRENT_DATE
    )::int AS checked_in_today_count,
    -- retention_day7/14/30: % of participants old enough to judge (joined >= N
    -- days ago) who are still active now.
    -- COALESCE to 0 (not NULL): a brand-new challenge with nobody old enough
    -- to judge yet is the common case, not an edge case, and the generated
    -- Go field is a plain (non-pointer) float64 — a real NULL here would be
    -- a runtime scan error, not just an ugly response.
    COALESCE(ROUND(100.0 * COUNT(uc.id) FILTER (WHERE uc.status = 'active' AND uc.joined_at <= now() - interval '7 days')
        / NULLIF(COUNT(uc.id) FILTER (WHERE uc.joined_at <= now() - interval '7 days'), 0)::numeric, 1), 0)::float8 AS retention_day7,
    COALESCE(ROUND(100.0 * COUNT(uc.id) FILTER (WHERE uc.status = 'active' AND uc.joined_at <= now() - interval '14 days')
        / NULLIF(COUNT(uc.id) FILTER (WHERE uc.joined_at <= now() - interval '14 days'), 0)::numeric, 1), 0)::float8 AS retention_day14,
    COALESCE(ROUND(100.0 * COUNT(uc.id) FILTER (WHERE uc.status = 'active' AND uc.joined_at <= now() - interval '30 days')
        / NULLIF(COUNT(uc.id) FILTER (WHERE uc.joined_at <= now() - interval '30 days'), 0)::numeric, 1), 0)::float8 AS retention_day30
FROM user_challenges uc
LEFT JOIN streaks s ON s.user_challenge_id = uc.id -- 1:1 with user_challenges, safe to join directly
WHERE uc.challenge_id = $1
`

type ChallengeAnalyticsRow struct {
	ActiveCount         int32   `json:"active_count"`
	LeftCount           int32   `json:"left_count"`
	DisqualifiedCount   int32   `json:"disqualified_count"`
	AvgCurrentStreak    float64 `json:"avg_current_streak"`
	CheckedInTodayCount int32   `json:"checked_in_today_count"`
	RetentionDay7       float64 `json:"retention_day7"`
	RetentionDay14      float64 `json:"retention_day14"`
	RetentionDay30      float64 `json:"retention_day30"`
}

// Retention here is a snapshot approximation, not true day-by-day cohort
// tracking: "still active at day N" means "joined >= N days ago and hasn't
// left/been disqualified as of right now" — we don't store historical daily
// state, so this can't reconstruct what was true exactly on day N for a
// cohort, only what's true currently for participants old enough to judge.
// checked_in_today_count is a correlated subquery, not a joined-and-counted
// column: checkins is one-to-many against user_challenges (one row per day),
// so joining it directly into this query's FROM would fan out every other
// aggregate here in proportion to how many check-ins each participant has
// — a real bug caught by testing against known ground truth, not assumed
// correct because it type-checked.
func (q *Queries) ChallengeAnalytics(ctx context.Context, challengeID pgtype.UUID) (ChallengeAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, challengeAnalytics, challengeID)
	var i ChallengeAnalyticsRow
	err := row.Scan(
		&i.ActiveCount,
		&i.LeftCount,
		&i.DisqualifiedCount,
		&i.AvgCurrentStreak,
		&i.CheckedInTodayCount,
		&i.RetentionDay7,
		&i.RetentionDay14,
		&i.RetentionDay30,
	)
	return i, err
}

const userSummary = `-- name: UserSummary :one
SELECT
    COUNT(uc.id)::int AS total_challenges,
    COUNT(uc.id) FILTER (WHERE uc.status = 'active')::int AS active_challenges,
    COUNT(uc.id) FILTER (WHERE uc.status = 'left')::int AS left_challenges,
    COUNT(uc.id) FILTER (WHERE uc.status = 'disqualified')::int AS disqualified_challenges,
    COALESCE(MAX(s.longest_streak), 0)::int AS best_streak_ever,
    COALESCE((SELECT SUM(wt.delta) FROM wallet_transactions wt WHERE wt.user_id = $1), 0)::bigint AS lifetime_coins
FROM user_challenges uc
LEFT JOIN streaks s ON s.user_challenge_id = uc.id
WHERE uc.user_id = $1
`

type UserSummaryRow struct {
	TotalChallenges        int32 `json:"total_challenges"`
	ActiveChallenges       int32 `json:"active_challenges"`
	LeftChallenges         int32 `json:"left_challenges"`
	DisqualifiedChallenges int32 `json:"disqualified_challenges"`
	BestStreakEver         int32 `json:"best_streak_ever"`
	LifetimeCoins          int64 `json:"lifetime_coins"`
}

// Lifetime progress/growth view across every challenge the user has ever
// joined — complements the per-challenge trend/adherence endpoints, which
// only look at one user_challenge at a time.
func (q *Queries) UserSummary(ctx context.Context, userID pgtype.UUID) (UserSummaryRow, error) {
	row := q.db.QueryRow(ctx, userSummary, userID)
	var i UserSummaryRow
	err := row.Scan(
		&i.TotalChallenges,
		&i.ActiveChallenges,
		&i.LeftChallenges,
		&i.DisqualifiedChallenges,
		&i.BestStreakEver,
		&i.LifetimeCoins,
	)
	return i, err
}
