// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkins.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCheckin = `-- name: InsertCheckin :one
INSERT INTO checkins (user_challenge_id, metric_data, verification_status)
VALUES ($1, $2, 'auto_approved')
RETURNING id, user_challenge_id, date, verification_status, metric_data, created_at
`

type InsertCheckinParams struct {
	UserChallengeID pgtype.UUID     `json:"user_challenge_id"`
	MetricData      json.RawMessage `json:"metric_data"`
}

func (q *Queries) InsertCheckin(ctx context.Context, arg InsertCheckinParams) (Checkin, error) {
	row := q.db.QueryRow(ctx, insertCheckin, arg.UserChallengeID, arg.MetricData)
	var i Checkin
	err := row.Scan(
		&i.ID,
		&i.UserChallengeID,
		&i.Date,
		&i.VerificationStatus,
		&i.MetricData,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckinsForUserChallenge = `-- name: ListCheckinsForUserChallenge :many
SELECT id, date, metric_data
FROM checkins
WHERE user_challenge_id = $1
ORDER BY date
`

type ListCheckinsForUserChallengeRow struct {
	ID         pgtype.UUID     `json:"id"`
	Date       pgtype.Date     `json:"date"`
	MetricData json.RawMessage `json:"metric_data"`
}

func (q *Queries) ListCheckinsForUserChallenge(ctx context.Context, userChallengeID pgtype.UUID) ([]ListCheckinsForUserChallengeRow, error) {
	rows, err := q.db.Query(ctx, listCheckinsForUserChallenge, userChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCheckinsForUserChallengeRow
	for rows.Next() {
		var i ListCheckinsForUserChallengeRow
		if err := rows.Scan(&i.ID, &i.Date, &i.MetricData); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
