// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const leaderboardForChallenge = `-- name: LeaderboardForChallenge :many
SELECT uc.id AS user_challenge_id, u.id AS user_id, u.name,
       COALESCE(s.current_streak, 0) AS current_streak
FROM user_challenges uc
JOIN users u ON u.id = uc.user_id
LEFT JOIN streaks s ON s.user_challenge_id = uc.id
WHERE uc.challenge_id = $1
ORDER BY current_streak DESC, uc.joined_at ASC
LIMIT 50
`

type LeaderboardForChallengeRow struct {
	UserChallengeID pgtype.UUID `json:"user_challenge_id"`
	UserID          pgtype.UUID `json:"user_id"`
	Name            string      `json:"name"`
	CurrentStreak   int32       `json:"current_streak"`
}

func (q *Queries) LeaderboardForChallenge(ctx context.Context, challengeID pgtype.UUID) ([]LeaderboardForChallengeRow, error) {
	rows, err := q.db.Query(ctx, leaderboardForChallenge, challengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardForChallengeRow
	for rows.Next() {
		var i LeaderboardForChallengeRow
		if err := rows.Scan(
			&i.UserChallengeID,
			&i.UserID,
			&i.Name,
			&i.CurrentStreak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
