// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveChallenges = `-- name: ListActiveChallenges :many
SELECT c.id, c.title, c.vertical_id, v.key AS vertical_key, c.influencer_handle,
       c.difficulty_stat, c.is_template,
       COUNT(uc.id) FILTER (WHERE uc.status = 'active')::int AS member_count
FROM challenges c
JOIN verticals v ON v.id = c.vertical_id
LEFT JOIN user_challenges uc ON uc.challenge_id = c.id
GROUP BY c.id, c.title, c.vertical_id, v.key, c.influencer_handle, c.difficulty_stat, c.is_template
ORDER BY member_count DESC
`

type ListActiveChallengesRow struct {
	ID               pgtype.UUID `json:"id"`
	Title            string      `json:"title"`
	VerticalID       pgtype.UUID `json:"vertical_id"`
	VerticalKey      string      `json:"vertical_key"`
	InfluencerHandle *string     `json:"influencer_handle"`
	DifficultyStat   *string     `json:"difficulty_stat"`
	IsTemplate       bool        `json:"is_template"`
	MemberCount      int32       `json:"member_count"`
}

// member_count is computed live from active participants, never stored, so
// it can't drift from reality the way a manually incremented counter can.
func (q *Queries) ListActiveChallenges(ctx context.Context) ([]ListActiveChallengesRow, error) {
	rows, err := q.db.Query(ctx, listActiveChallenges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveChallengesRow
	for rows.Next() {
		var i ListActiveChallengesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.VerticalID,
			&i.VerticalKey,
			&i.InfluencerHandle,
			&i.DifficultyStat,
			&i.IsTemplate,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRedemptionItems = `-- name: ListActiveRedemptionItems :many
SELECT id, type, title, coin_cost, metadata
FROM redemption_items
WHERE active = true
ORDER BY coin_cost
`

type ListActiveRedemptionItemsRow struct {
	ID       pgtype.UUID     `json:"id"`
	Type     string          `json:"type"`
	Title    string          `json:"title"`
	CoinCost int32           `json:"coin_cost"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) ListActiveRedemptionItems(ctx context.Context) ([]ListActiveRedemptionItemsRow, error) {
	rows, err := q.db.Query(ctx, listActiveRedemptionItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRedemptionItemsRow
	for rows.Next() {
		var i ListActiveRedemptionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.CoinCost,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerticals = `-- name: ListVerticals :many
SELECT id, key, label, icon, input_schema
FROM verticals
ORDER BY label
`

type ListVerticalsRow struct {
	ID          pgtype.UUID     `json:"id"`
	Key         string          `json:"key"`
	Label       string          `json:"label"`
	Icon        *string         `json:"icon"`
	InputSchema json.RawMessage `json:"input_schema"`
}

func (q *Queries) ListVerticals(ctx context.Context) ([]ListVerticalsRow, error) {
	rows, err := q.db.Query(ctx, listVerticals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerticalsRow
	for rows.Next() {
		var i ListVerticalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Icon,
			&i.InputSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
