// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adherenceByDayOfWeek = `-- name: AdherenceByDayOfWeek :many
SELECT EXTRACT(dow FROM date)::int AS day_of_week, COUNT(*)::int AS checkin_count
FROM checkins
WHERE user_challenge_id = $1
GROUP BY EXTRACT(dow FROM date)
ORDER BY day_of_week
`

type AdherenceByDayOfWeekRow struct {
	DayOfWeek    int32 `json:"day_of_week"`
	CheckinCount int32 `json:"checkin_count"`
}

func (q *Queries) AdherenceByDayOfWeek(ctx context.Context, userChallengeID pgtype.UUID) ([]AdherenceByDayOfWeekRow, error) {
	rows, err := q.db.Query(ctx, adherenceByDayOfWeek, userChallengeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdherenceByDayOfWeekRow
	for rows.Next() {
		var i AdherenceByDayOfWeekRow
		if err := rows.Scan(&i.DayOfWeek, &i.CheckinCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trendForUserChallenge = `-- name: TrendForUserChallenge :many
SELECT date, (metric_data ->> $2::text)::float8 AS value
FROM checkins
WHERE user_challenge_id = $1
  AND metric_data ? $2::text
ORDER BY date
`

type TrendForUserChallengeParams struct {
	UserChallengeID pgtype.UUID `json:"user_challenge_id"`
	FieldKey        string      `json:"field_key"`
}

type TrendForUserChallengeRow struct {
	Date  pgtype.Date `json:"date"`
	Value float64     `json:"value"`
}

// Generic trend series: one numeric value per check-in date, picked from
// metric_data by field key (e.g. "weight_kg", "pages") — the caller supplies
// which key to project since that differs per vertical.
func (q *Queries) TrendForUserChallenge(ctx context.Context, arg TrendForUserChallengeParams) ([]TrendForUserChallengeRow, error) {
	rows, err := q.db.Query(ctx, trendForUserChallenge, arg.UserChallengeID, arg.FieldKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrendForUserChallengeRow
	for rows.Next() {
		var i TrendForUserChallengeRow
		if err := rows.Scan(&i.Date, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
