// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Challenge struct {
	ID                        pgtype.UUID        `json:"id"`
	Title                     string             `json:"title"`
	VerticalID                pgtype.UUID        `json:"vertical_id"`
	InfluencerHandle          *string            `json:"influencer_handle"`
	DifficultyStat            *string            `json:"difficulty_stat"`
	IsTemplate                bool               `json:"is_template"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	DisqualifyAfterMissedDays *int32             `json:"disqualify_after_missed_days"`
}

type Checkin struct {
	ID                 pgtype.UUID        `json:"id"`
	UserChallengeID    pgtype.UUID        `json:"user_challenge_id"`
	Date               pgtype.Date        `json:"date"`
	VerificationStatus string             `json:"verification_status"`
	MetricData         json.RawMessage    `json:"metric_data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Follow struct {
	FollowerID pgtype.UUID        `json:"follower_id"`
	FolloweeID pgtype.UUID        `json:"followee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Redemption struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RedemptionItemID pgtype.UUID        `json:"redemption_item_id"`
	CodeOrSlot       *string            `json:"code_or_slot"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type RedemptionItem struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	CoinCost  int32              `json:"coin_cost"`
	Metadata  json.RawMessage    `json:"metadata"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Streak struct {
	UserChallengeID pgtype.UUID        `json:"user_challenge_id"`
	CurrentStreak   int32              `json:"current_streak"`
	LongestStreak   int32              `json:"longest_streak"`
	LastCheckinDate pgtype.Date        `json:"last_checkin_date"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	AuthMethod  string             `json:"auth_method"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	LoginCount  int32              `json:"login_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UserChallenge struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ChallengeID    pgtype.UUID        `json:"challenge_id"`
	CustomGoal     []byte             `json:"custom_goal"`
	Status         string             `json:"status"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	LeftAt         pgtype.Timestamptz `json:"left_at"`
	DisqualifiedAt pgtype.Timestamptz `json:"disqualified_at"`
}

type Vertical struct {
	ID          pgtype.UUID        `json:"id"`
	Key         string             `json:"key"`
	Label       string             `json:"label"`
	Icon        *string            `json:"icon"`
	InputSchema json.RawMessage    `json:"input_schema"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WalletTransaction struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Delta     int32              `json:"delta"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
