// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redemptions.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRedemptionItem = `-- name: GetRedemptionItem :one
SELECT id, type, title, coin_cost, metadata, active
FROM redemption_items
WHERE id = $1
`

type GetRedemptionItemRow struct {
	ID       pgtype.UUID     `json:"id"`
	Type     string          `json:"type"`
	Title    string          `json:"title"`
	CoinCost int32           `json:"coin_cost"`
	Metadata json.RawMessage `json:"metadata"`
	Active   bool            `json:"active"`
}

func (q *Queries) GetRedemptionItem(ctx context.Context, id pgtype.UUID) (GetRedemptionItemRow, error) {
	row := q.db.QueryRow(ctx, getRedemptionItem, id)
	var i GetRedemptionItemRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.CoinCost,
		&i.Metadata,
		&i.Active,
	)
	return i, err
}

const insertRedemption = `-- name: InsertRedemption :one
INSERT INTO redemptions (user_id, redemption_item_id, code_or_slot)
VALUES ($1, $2, $3)
RETURNING id, user_id, redemption_item_id, code_or_slot, created_at
`

type InsertRedemptionParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	RedemptionItemID pgtype.UUID `json:"redemption_item_id"`
	CodeOrSlot       *string     `json:"code_or_slot"`
}

func (q *Queries) InsertRedemption(ctx context.Context, arg InsertRedemptionParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, insertRedemption, arg.UserID, arg.RedemptionItemID, arg.CodeOrSlot)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RedemptionItemID,
		&i.CodeOrSlot,
		&i.CreatedAt,
	)
	return i, err
}

const listRedemptionsForUser = `-- name: ListRedemptionsForUser :many
SELECT r.id, r.code_or_slot, r.created_at,
       ri.title, ri.type, ri.coin_cost
FROM redemptions r
JOIN redemption_items ri ON ri.id = r.redemption_item_id
WHERE r.user_id = $1
ORDER BY r.created_at DESC
`

type ListRedemptionsForUserRow struct {
	ID         pgtype.UUID        `json:"id"`
	CodeOrSlot *string            `json:"code_or_slot"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Title      string             `json:"title"`
	Type       string             `json:"type"`
	CoinCost   int32              `json:"coin_cost"`
}

func (q *Queries) ListRedemptionsForUser(ctx context.Context, userID pgtype.UUID) ([]ListRedemptionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listRedemptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRedemptionsForUserRow
	for rows.Next() {
		var i ListRedemptionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CodeOrSlot,
			&i.CreatedAt,
			&i.Title,
			&i.Type,
			&i.CoinCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
