// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streaks.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStreak = `-- name: GetStreak :one
SELECT user_challenge_id, current_streak, longest_streak, last_checkin_date
FROM streaks
WHERE user_challenge_id = $1
`

type GetStreakRow struct {
	UserChallengeID pgtype.UUID `json:"user_challenge_id"`
	CurrentStreak   int32       `json:"current_streak"`
	LongestStreak   int32       `json:"longest_streak"`
	LastCheckinDate pgtype.Date `json:"last_checkin_date"`
}

func (q *Queries) GetStreak(ctx context.Context, userChallengeID pgtype.UUID) (GetStreakRow, error) {
	row := q.db.QueryRow(ctx, getStreak, userChallengeID)
	var i GetStreakRow
	err := row.Scan(
		&i.UserChallengeID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastCheckinDate,
	)
	return i, err
}

const upsertStreak = `-- name: UpsertStreak :one
INSERT INTO streaks (user_challenge_id, current_streak, longest_streak, last_checkin_date, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_challenge_id)
DO UPDATE SET current_streak = $2, longest_streak = $3, last_checkin_date = $4, updated_at = now()
RETURNING user_challenge_id, current_streak, longest_streak, last_checkin_date
`

type UpsertStreakParams struct {
	UserChallengeID pgtype.UUID `json:"user_challenge_id"`
	CurrentStreak   int32       `json:"current_streak"`
	LongestStreak   int32       `json:"longest_streak"`
	LastCheckinDate pgtype.Date `json:"last_checkin_date"`
}

type UpsertStreakRow struct {
	UserChallengeID pgtype.UUID `json:"user_challenge_id"`
	CurrentStreak   int32       `json:"current_streak"`
	LongestStreak   int32       `json:"longest_streak"`
	LastCheckinDate pgtype.Date `json:"last_checkin_date"`
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) (UpsertStreakRow, error) {
	row := q.db.QueryRow(ctx, upsertStreak,
		arg.UserChallengeID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastCheckinDate,
	)
	var i UpsertStreakRow
	err := row.Scan(
		&i.UserChallengeID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastCheckinDate,
	)
	return i, err
}
