// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_challenges.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserChallenge = `-- name: CreateUserChallenge :one
INSERT INTO user_challenges (user_id, challenge_id, custom_goal)
VALUES ($1, $2, $3)
RETURNING id, user_id, challenge_id, custom_goal, status, joined_at
`

type CreateUserChallengeParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ChallengeID pgtype.UUID `json:"challenge_id"`
	CustomGoal  []byte      `json:"custom_goal"`
}

func (q *Queries) CreateUserChallenge(ctx context.Context, arg CreateUserChallengeParams) (UserChallenge, error) {
	row := q.db.QueryRow(ctx, createUserChallenge, arg.UserID, arg.ChallengeID, arg.CustomGoal)
	var i UserChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.CustomGoal,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const getUserChallengeWithVertical = `-- name: GetUserChallengeWithVertical :one
SELECT uc.id, uc.user_id, uc.challenge_id, uc.status,
       c.vertical_id, v.key AS vertical_key, v.input_schema
FROM user_challenges uc
JOIN challenges c ON c.id = uc.challenge_id
JOIN verticals v ON v.id = c.vertical_id
WHERE uc.id = $1
`

type GetUserChallengeWithVerticalRow struct {
	ID          pgtype.UUID     `json:"id"`
	UserID      pgtype.UUID     `json:"user_id"`
	ChallengeID pgtype.UUID     `json:"challenge_id"`
	Status      string          `json:"status"`
	VerticalID  pgtype.UUID     `json:"vertical_id"`
	VerticalKey string          `json:"vertical_key"`
	InputSchema json.RawMessage `json:"input_schema"`
}

func (q *Queries) GetUserChallengeWithVertical(ctx context.Context, id pgtype.UUID) (GetUserChallengeWithVerticalRow, error) {
	row := q.db.QueryRow(ctx, getUserChallengeWithVertical, id)
	var i GetUserChallengeWithVerticalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.Status,
		&i.VerticalID,
		&i.VerticalKey,
		&i.InputSchema,
	)
	return i, err
}

const listUserChallengesForUser = `-- name: ListUserChallengesForUser :many
SELECT uc.id, uc.status, uc.joined_at,
       c.title AS challenge_title, c.influencer_handle,
       v.key AS vertical_key, v.label AS vertical_label,
       COALESCE(s.current_streak, 0) AS current_streak,
       COALESCE(s.longest_streak, 0) AS longest_streak,
       s.last_checkin_date
FROM user_challenges uc
JOIN challenges c ON c.id = uc.challenge_id
JOIN verticals v ON v.id = c.vertical_id
LEFT JOIN streaks s ON s.user_challenge_id = uc.id
WHERE uc.user_id = $1
ORDER BY uc.joined_at DESC
`

type ListUserChallengesForUserRow struct {
	ID               pgtype.UUID        `json:"id"`
	Status           string             `json:"status"`
	JoinedAt         pgtype.Timestamptz `json:"joined_at"`
	ChallengeTitle   string             `json:"challenge_title"`
	InfluencerHandle *string            `json:"influencer_handle"`
	VerticalKey      string             `json:"vertical_key"`
	VerticalLabel    string             `json:"vertical_label"`
	CurrentStreak    int32              `json:"current_streak"`
	LongestStreak    int32              `json:"longest_streak"`
	LastCheckinDate  pgtype.Date        `json:"last_checkin_date"`
}

func (q *Queries) ListUserChallengesForUser(ctx context.Context, userID pgtype.UUID) ([]ListUserChallengesForUserRow, error) {
	rows, err := q.db.Query(ctx, listUserChallengesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserChallengesForUserRow
	for rows.Next() {
		var i ListUserChallengesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.JoinedAt,
			&i.ChallengeTitle,
			&i.InfluencerHandle,
			&i.VerticalKey,
			&i.VerticalLabel,
			&i.CurrentStreak,
			&i.LongestStreak,
			&i.LastCheckinDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
