// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, auth_method)
VALUES ($1, $2, $3)
RETURNING id, name, email, phone, auth_method, last_login_at, login_count, created_at
`

type CreateUserParams struct {
	Name       string  `json:"name"`
	Email      *string `json:"email"`
	AuthMethod string  `json:"auth_method"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.AuthMethod)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.AuthMethod,
		&i.LastLoginAt,
		&i.LoginCount,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, auth_method, last_login_at, login_count, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.AuthMethod,
		&i.LastLoginAt,
		&i.LoginCount,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, auth_method, last_login_at, login_count, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.AuthMethod,
		&i.LastLoginAt,
		&i.LoginCount,
		&i.CreatedAt,
	)
	return i, err
}

const lockUserForRedemption = `-- name: LockUserForRedemption :exec
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

// Locks the user's row for the duration of the transaction so two concurrent
// redemption requests for the same user serialize instead of racing on balance.
func (q *Queries) LockUserForRedemption(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockUserForRedemption, id)
	return err
}

const recordLogin = `-- name: RecordLogin :exec
UPDATE users
SET last_login_at = now(), login_count = login_count + 1
WHERE id = $1
`

func (q *Queries) RecordLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordLogin, id)
	return err
}
