// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBalance = `-- name: GetBalance :one
SELECT COALESCE(SUM(delta), 0)::bigint AS balance
FROM wallet_transactions
WHERE user_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const insertWalletTransaction = `-- name: InsertWalletTransaction :one
INSERT INTO wallet_transactions (user_id, delta, reason)
VALUES ($1, $2, $3)
RETURNING id, user_id, delta, reason, created_at
`

type InsertWalletTransactionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Delta  int32       `json:"delta"`
	Reason string      `json:"reason"`
}

func (q *Queries) InsertWalletTransaction(ctx context.Context, arg InsertWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, insertWalletTransaction, arg.UserID, arg.Delta, arg.Reason)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Delta,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, delta, reason, created_at
FROM wallet_transactions
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListWalletTransactionsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Delta     int32              `json:"delta"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, userID pgtype.UUID) ([]ListWalletTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWalletTransactionsRow
	for rows.Next() {
		var i ListWalletTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Delta,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
